name: Multi-Platform Build
on: [push] # , pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        app: [CherryRa1n, prerun]
        exclude:
          - app: prerun
            os: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libglu1-mesa-dev freeglut3-dev

      - name: Cache wxWidgets
        uses: actions/cache@v4
        with:
          path: build/_deps
          key: ${{ runner.os }}-wx-v3.3.2-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-wx-v3.3.2-

      - name: Configure CMake
        run: cmake -S ${{ matrix.app }} -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build App
        run: cmake --build build --config Release --parallel 2

      - name: upload finished program
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.app }}-binary
          path: |
            config.json
            build/release/*.exe
            build/${{ matrix.app }}
            build/*.app
